### ISSUE TITLE
Unify data build

### ISSUE THREAD

**Issue by rajbhargava** [huntallcott/Lotteries#31] opened 2019-06-25 22:19 UTC
@huntallcott @bblockwood: As we discussed [last Friday](https://docs.google.com/document/d/1HgfpQmScsz-qcGzgbOIHgD-fZ94AoOv4OjHpZUpr0do/edit#heading=h.5fke2lbd621s), opening up this issue to document all issues and analyses related to unifying #20 and #26. I am all caught up with the previous code and analyses, and can spend a significant portion of the next two weeks pushing this forward as much as possible. 

My understanding is that we want to merge together the PB/MM state-level data with the game-level data that Andrew has collected, and then estimate income effects and demand elasticity from the combined data. Let me know if that seems (in)correct!

**Comment by huntallcott** [comment] 2019-06-26 11:41
Here's how I understand the goal of this issue:
1. Re-org the `build/code` folder so that the game-by-week LaFleur data is created once in one subfolder using a file called dataprep_lafleurs.do, using the best cleaning code that @anjoung developed (which is both in the income effects and demand elasticity areas) and indicating the state x games that don't have sufficiently long balanced panels, as we had done in the income effects estimation. The goal here is to have one consistent data prep routine for the LaFleur's data.
2. After that prep is done, there is a final build script that finalizes the data for estimating income effects `/build/code/income_effects.do`, which includes (i) collapsing to the game-by-quarter level and (ii) merging other data such as the income data. 
3. There is a separate final build script for he demand elasticity estimation, `/build/code/demand_elasticity.do`, which includes merging other data such as the PB/MM and other jackpot data.
Then from there we'll close this issue and move to separate issues for the income effects and demand elasticity analysis.

**Comment by bblockwood** [comment] 2019-06-26 14:10
I agree with @huntallcott's understanding. 

On addition — I received a CD from Florida with some additional data! It looks mostly like more geographically granular sales data (month x game x store) and granular prize winnings data. As a result, I don't *think* it will displace or add to anything for this current analysis, as we already had LaFleur's data for sales and prize data by game. But @rajbhargava can you take a look and confirm that suspicion? (The raw data is in `dropbox/DataStorageCodebooks/State Lotteries/prize data/FL/prize sales microdata/`.) Thanks!

**Comment by rajbhargava** [comment] 2019-06-26 15:34
Got it, sounds good.

@bblockwood yep, there doesn't seem to be any additional data beyond what we already have from LaFleur's.

**Comment by rajbhargava** [comment] 2019-07-03 20:00
@huntallcott @bblockwood:

I went through and re-organized the code, fixing mistakes and addressing issues when necessary. The four new and improved files are in build/code/unified. MakeLaFleursData.do combines all the LaFleurs data, MakeCombinedLotteryData.do merges in all other data (including PB/MM and income), CollapseQuarters.do takes the fully merged data and collapses it to the game-by-quarter level, and DataChecks.do combines the code checking/visualizations that were previously done in issue sub-folders. 

The most immediate changes are that:
- MakeCombinedLotteryData.do produces a file data/intermediate/lotteries.dta that contains sales, income, CPI, odds, and prize data for LaFleurs, PB/MM, and state-level games (which is then collapsed for income effects).
- I addressed Andrew's to-do's of fixing lagged EVs across games, draw structures, and discontinuities. The way lagged EV is currently constructed is: latest EV from the calendar week (or most recent EV if not available in the last calendar week) previous to the draw date. I don't know if this is the most natural way to construct lagged EV (in theory this means that lagged EV could be from yesterday; in practice lagged EV is generally from 3-7 days ago), but it can be justified if we assume that people check lottery EVs every weekend/beginning of the week. I drop lagged EV if the last draw was over 14 days ago. Finally, following Andrew's in-code instructions, I drop lagged EV every time is a new draw structure (i.e. there are a new amount of draws per week), which is ~1.6% of our data.

**Comment by bblockwood** [comment] 2019-07-04 11:22
@rajbhargava thanks for your great work on this, it's great to have a cleaned version of this data. This is a fine way to handle lagged EV — the goal was to avoid just measuring a mechanical relationship between sales and jackpots, as some lotteries allocate sales to the contemporaneous jackpot. Using a lagged jackpot value (even if the lag is only one day) addresses that. 

@huntallcott should weigh in if he disagrees, but as a next step, I think it would be very helpful to compile exported results for both the income effects and elasticity estimation results, in PDF form, as you did for the MTurk results, with results in the `paper` directory. We can return to #20 and #26 for both those issues, and close this one. For #20, I think this amounts to moving over and re-running the income effects analysis [here](https://github.com/huntallcott/Lotteries/blob/master/Issues/20/Income%20effects%20estimation.pdf), with the new data. For #26, I think we want to generate binscatters plots like in Figure 2 of [this file](https://github.com/huntallcott/Lotteries/blob/master/Issues/26/demand_estimation_notes.pdf). It would be nice to start with a figure that replicates Figure 2 exactly (using the updated data), then another which controls for state x game x quarter-of-sample, along with regression tables that show the coefficient on EV. 

These ideas are all subject to modification by @huntallcott or @dtaubinsky, of course, and feel free to add suggestions or flag issues now that you are familiar with the data! Thanks again for your great work.

**Closed by bblockwood** 2019-07-04 11:22 UTC

**Comment by huntallcott** [comment] 2019-07-04 16:06
Thanks very much @rajbhargava. This is looking good and much appreciated.

A few minor comments:
1. Please run the relevant directory with every commit. Right now there appear to be legacy files in dropbox/Data/ -- it should be that all of the .dta files on dropbox have a date of July 3, right?
2. I note that we are violating the standard structure by keeping all data (not just large data) on dropbox. This seems OK for now (because I don’t want the repo size to get too big, and it seems fine to have all the data in the same place for now) but could be flagged for the future. Also OK to not have the make.py files, but eventually once things settle down let's add them.
3. Can you take just one more pass at dropping unneeded variables and consolidating code. For example:
   - What is the difference between qyear and YQ? I think none. What about just having YQ?
   - I’d be fine dropping state_full to reduce file size unless I’m missing something there. If we ever need it for a figure or something, we could merge it back in easily.
   - Can we drop the _merge variable in lotteries.dta? (In general I don't think datasets should have _merge variables in them.
   - I suspect that the game_s variable is not needed given we already have game and state and id.
   - Seems like further refactoring can be done, e.g. in MakeBEA.do we redefine state names multiple times, e.g. on lines 205 and then 254.

I otherwise agree with @bblockwood's next steps. And ideally, it would be great to have these results in advance of our meeting early next week?

Thanks again and happy July 4th to everybody!

**Comment by rajbhargava** [comment] 2019-07-05 14:11
@huntallcott: 

Deleted all legacy files, took one more pass through the cleaning files for BEA/CPI/state-level data, and dropped unnecessary variables. Ready to move onto the next steps!

**Comment by huntallcott** [comment] 2019-07-05 15:46
Fantastic, thanks! 
1, 3. I still note that there are files in Dropbox\Lotteries\Data\intermediate\LotterySalesData\ that have save date 5/23. This seems wrong? Can you take a second look at these legacy files?

Then, were the next steps clear? Let us know if questions.

**Comment by rajbhargava** [comment] 2019-07-08 22:46
@bblockwood @huntallcott:

I've replicated results for both the income effects and elasticity estimation results as specified, with the compiled pdf [here](https://github.com/huntallcott/Lotteries/blob/master/paper/output/Analysis.pdf). Let me know if there's any accompanying analysis you think would be useful (in the threads for #20/#26!)

Re: legacy files. awaiting clarification from Andrew on a few states, but removed all of them in the meantime.
