### ISSUE TITLE
Clean and analyze MTurk pilot survey data

### ISSUE THREAD

**Issue by bblockwood** [huntallcott/Lotteries#7] opened 2018-06-25 13:39 UTC
The deliverable for this issue is a cleaned (Stata) data set of the MTurk pilot data, with preliminary analysis.

**Comment by bblockwood** [comment] 2018-06-25 13:41
@anjoung: please begin by adding code to *github/Code/Build/DataPrep.do* to import and format the .tsv raw data, following the protocols we used for the soda tax survey. (E.g., Stata sets the userpath based on who is running the code.)

As a first step in analysis, could you regress and plot lottery and scratch ticket spending against household income?

Thanks!

**Comment by anjoung** [comment] 2018-06-25 14:01
@bblockwood Got it! Also, should I just compile a bunch of summary statistics in a Google Doc like normal or would you just like the regression and plot to start?

**Comment by bblockwood** [comment] 2018-06-25 14:04
@anjoung yes please create a google doc, and just make the regression and plot the highest-priority things to post there. Then it would be great if you explore other summary statistics there as well.

**Comment by anjoung** [comment] 2018-06-25 19:38
Created a Google Doc. It is currently very sparse, but I'll start filling it up as soon as all the data cleaned, organized, and analyzed.

https://docs.google.com/document/d/1wC3C66Aw1zSt0VUanZIpxZFM43Z4OEhl-hO-InT0TFI/edit?usp=sharing

**Comment by anjoung** [comment] 2018-06-26 17:08
@bblockwood Just updated the Google Doc. Let me know if anything is confusing or if I should give it another swing.

**Comment by bblockwood** [comment] 2018-06-26 21:36
Thanks @anjoung. Interesting we're getting positive point estimates of income on lottery expenditures. 

@jackblun: this is now to the point where it might be helpful for you to chime in and work with @anjoung on calculating hypothetical demand treatment effects. Can you take the lead on that, and post any questions and updates here? (@anjoung can continue to paste results in the Google doc.) 

Thanks!

**Comment by jackblun** [comment] 2018-06-27 08:28
@anjoung this is great, thanks. First thing, I can't find your code in the GitHub. Could you direct me to it? 

I'm then happy to build on your code to do the following:
1) For some additional income regressions, pool the lowest two categories and drop the very top category. That way we will have four equal bins for income.
2) Scatter plot of indifference points in table 1 vs table 2
3) For the hypothetical choices: regressions to calculate treatment effect on indifference point in table 1, indifference point in table 2, and the difference in indifference points for both
4) For the actual megamillions choice: regression to calculate treatment effect on indifference point
5) For all of the above regressions, also try controlling for answers to preference question, and reported income

**Comment by anjoung** [comment] 2018-06-27 14:07
@jackblun Sorry! Just pushed everything. The two files you would be most interested in are:
1.  _LotteriesGithub_/Code/SetGlobals <-- Run this before everything
2.  _LotteriesGithub_/Code/Build/Data Prep <-- Run this to get cleaned data
3.  _LotteriesGithub_/Code/Analysis/InitialAnalysis Pilot_v1 <-- Preliminary analysis

Let me know if there's anything that I should do! Otherwise, I'll keep working on just wrapping up compiling a few more summary stats.

**Comment by jackblun** [comment] 2018-06-27 15:53
@anjoung brilliant, I'll focus on the treatment effect side.

**Comment by jackblun** [comment] 2018-06-27 20:34
@anjoung @bblockwood I've done some initial simple treatment effect analysis and briefly written this up in the file [here](https://docs.google.com/document/d/1wC3C66Aw1zSt0VUanZIpxZFM43Z4OEhl-hO-InT0TFI/edit#).

@anjoung, I've left the summary statistics to you for now. A few you will want to include:
1) Distribution of hypothetical choice responses and changes in responses between the two
2) Relationship between expected value answers and lottery spending

**Comment by jackblun** [comment] 2018-06-28 07:17
Hey @anjoung, could you adjust the income scaling to be consistent with the below quote from Clotfelter et al 1999?
"
We used numerical frequencies of 300 (6about every day5), 100 (61 to 3 times per week5), 18 (once or twice a month5), 8 (6a few days all year5), or 1 (6only one day in the past year5)
"
Could you also generate summary stats and regression results for **total** spending, the sum of scratchoffs and lotto? Let me know when this and other aspects of summary stats are done and I'll finish off the analysis and tidy things up.

**Comment by anjoung** [comment] 2018-06-28 19:56
@jackblun I adjusted the income scaling from the quote and I also generated a standard summary stats table and regression table using the total spending measure you mentioned.

**Comment by anjoung** [comment] 2018-06-29 14:28
@jackblun Just want to check-in about continuing to analyze the pilot data. I'm imagining that this is a lower priority than the analysis that Hunt outlined, but wondering if once I am done with that, if it is worth my time to continue digging into the pilot data, or if people are done looking at those results.

**Comment by jackblun** [comment] 2018-06-29 14:29
@anjoung I think you're right, prioritise the new stuff on the scratch-offs. If you could push your current stage of working on the MTurk pilot data I'll finish up the summary stats and analysis of that.

**Comment by anjoung** [comment] 2018-06-29 14:31
Just pushed it!

**Comment by jackblun** [comment] 2018-07-01 15:39
@dtaubinsky  @bblockwood  @huntallcott  @anjoung I've tidied up the code and pushed here. I also redid all the analysis and have written up results [here](https://docs.google.com/document/d/1wC3C66Aw1zSt0VUanZIpxZFM43Z4OEhl-hO-InT0TFI/edit#).
The code should all be clear should you want to play around with the data yourself.

We are seeing a lot more from this than at first glance. In particular, have a look at the relationship with income and lotto expenditure now that I have adopted a different approach to cleaning the expenditure reports. Also have a look at the treatment effects discussed in the final section.

@anjoung on the expenditure data, instead of winsorizing I decided to drop the exceptionally high reports as I think they likely reflect keyboard bashing by participants.

**Comment by huntallcott** [comment] 2018-07-01 18:09
@jackblun and @anjoung , this is really exceptional. I just took a look and am excited to discuss on Tuesday.

**Comment by bblockwood** [comment] 2018-07-02 01:20
Yes thanks guys -- these results are really informative and very helpfully presented. The across-income spending profile in particular is  interesting. Looking forward to talking!

**Comment by jackblun** [comment] 2018-07-04 08:40
@dtaubinsky @bblockwood @huntallcott  I've done some tests of the relationship between expected value calculation performance and choices. Written up towards the end of the doc [here](https://docs.google.com/document/d/1wC3C66Aw1zSt0VUanZIpxZFM43Z4OEhl-hO-InT0TFI/edit#)

In a nutshell, we see some evidence that those better at calculating expected values are more likely to be expected value maximizers in the small-odds setting. This is significant for the treatment group, but not quite in the control group. I also see the slightly odd result that among treated individuals, on average those responding correctly to the expected value calculations become more risk averse.

**Comment by dtaubinsky** [comment] 2018-07-04 17:35
@jackblun, excellent work! I wouldn't read into the treated group results too much, since those are hard to interpret. What we would want to report for the actual paper is just the correlations coming from the control group, which I find **extremely** encouraging. If these hold up in a larger sample, they will significantly add to the credibility of our interpretation of the EV treatment.

**Comment by huntallcott** [comment] 2018-07-27 22:20
closing this issue as I think it's done.

**Closed** 2018-07-30 17:58 UTC
